// <auto-generated />
using System;
using DailyNews.BusinessObject.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DailyNews.BusinessObject.Migrations
{
    [DbContext(typeof(DailyNewsContext))]
    [Migration("20231111060251_init_v2")]
    partial class init_v2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BusinessObject.Models.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticleId"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ArticleId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            ArticleId = 1,
                            CategoryId = 4,
                            Content = "Regular exercise has numerous benefits for your overall health. It can help you maintain a healthy weight, reduce the risk of chronic diseases, and improve your mood. Exercise is not just about physical fitness; it also enhances mental well-being. It can reduce stress and anxiety, boost self-esteem, and increase cognitive function. Whether it's a brisk walk, a yoga session, or a full-blown workout, make exercise a part of your daily routine for a healthier, happier life.",
                            CreatedDate = new DateTime(2023, 11, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "Stay active and healthy",
                            Title = "Benefits of Regular Exercise"
                        },
                        new
                        {
                            ArticleId = 2,
                            CategoryId = 4,
                            Content = "Maintaining healthy eating habits is essential for your well-being. A balanced diet rich in fruits, vegetables, and whole grains provides essential nutrients for your body. It can help prevent various health issues, including heart disease and diabetes. In addition, a proper diet can boost your energy levels and promote weight management. Start making mindful food choices today for a healthier lifestyle.",
                            CreatedDate = new DateTime(2023, 11, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "Nourish your body with the right food",
                            Title = "Healthy Eating Habits"
                        },
                        new
                        {
                            ArticleId = 3,
                            CategoryId = 3,
                            Content = "Time management is crucial in our fast-paced world. Properly managing your time can increase productivity and reduce stress. Prioritizing tasks, setting goals, and avoiding distractions are key components of effective time management. By optimizing your daily routine, you can achieve more in less time, leaving room for relaxation and personal growth.",
                            CreatedDate = new DateTime(2023, 11, 6, 11, 5, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "Maximize productivity and reduce stress",
                            Title = "Effective Time Management"
                        },
                        new
                        {
                            ArticleId = 4,
                            CategoryId = 4,
                            Content = "Getting enough quality sleep is essential for physical and mental health. Sleep allows your body to rest, repair, and recharge. It plays a vital role in memory consolidation and emotional well-being. Lack of sleep can lead to a range of health issues, including impaired cognitive function and mood disturbances. Prioritize your sleep schedule to lead a healthier and more productive life.",
                            CreatedDate = new DateTime(2023, 11, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "Rest for a healthier life",
                            Title = "The Importance of Sleep"
                        },
                        new
                        {
                            ArticleId = 5,
                            CategoryId = 1,
                            Content = "Politics is a complex field with a variety of ideologies. From conservatism to liberalism, socialism to libertarianism, it's essential to understand the different political beliefs that shape our world. Each ideology has its unique approach to governance, economics, and societal issues. By gaining insight into these ideologies, you can make informed political decisions and engage in meaningful discussions about the future of your nation.",
                            CreatedDate = new DateTime(2023, 11, 10, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "Exploring diverse political beliefs",
                            Title = "Understanding Political Ideologies"
                        },
                        new
                        {
                            ArticleId = 6,
                            CategoryId = 1,
                            Content = "Media plays a significant role in shaping public opinion and influencing political decisions. In the age of 24/7 news coverage and social media, understanding how media operates within the political landscape is crucial. It can influence elections, policy debates, and public discourse. Explore the relationship between media and politics to become a more informed citizen.",
                            CreatedDate = new DateTime(2023, 11, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "Media's impact on political landscape",
                            Title = "The Role of Media in Politics"
                        },
                        new
                        {
                            ArticleId = 7,
                            CategoryId = 1,
                            Content = "The world faces numerous political challenges, from climate change to international conflicts. Understanding and addressing these global issues is critical for a more stable and prosperous future. Explore the complexities of international politics and the interconnected nature of global challenges. Discover the efforts and initiatives aimed at finding solutions to these pressing problems.",
                            CreatedDate = new DateTime(2023, 11, 10, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "Addressing pressing global issues",
                            Title = "Global Political Challenges"
                        },
                        new
                        {
                            ArticleId = 8,
                            CategoryId = 2,
                            Content = "Economics is the study of how societies allocate their limited resources to meet their needs and wants. In this introductory article, we delve into the fundamental economic principles, including supply and demand, opportunity cost, and the role of markets in resource allocation. Understanding these concepts is crucial for making informed economic decisions in your personal and professional life.",
                            CreatedDate = new DateTime(2023, 11, 10, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "Exploring fundamental economic concepts",
                            Title = "Introduction to Economic Principles"
                        },
                        new
                        {
                            ArticleId = 9,
                            CategoryId = 2,
                            Content = "Inflation is a common economic phenomenon where the general price level of goods and services increases over time. This article explores the impact of inflation on individuals, businesses, and the overall economy. Learn how inflation can erode purchasing power, affect investment decisions, and influence monetary policy. Understanding inflation is essential for financial planning and economic analysis.",
                            CreatedDate = new DateTime(2023, 11, 10, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "Unpacking the effects of rising prices",
                            Title = "Impact of Inflation on the Economy"
                        },
                        new
                        {
                            ArticleId = 10,
                            CategoryId = 2,
                            Content = "International trade is a key driver of the global economy. This article delves into the intricacies of international trade, including the benefits of trade, trade agreements, and the impact of tariffs and trade barriers. Understand how global economic interdependence shapes the prosperity of nations and how international trade can impact various industries and markets.",
                            CreatedDate = new DateTime(2023, 11, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "Exploring the dynamics of global trade",
                            Title = "International Trade and Global Economics"
                        },
                        new
                        {
                            ArticleId = 11,
                            CategoryId = 3,
                            Content = "Finding the right balance between work and personal life is crucial for overall well-being. This article explores strategies for managing your professional responsibilities while making time for personal life, hobbies, and relaxation. Achieving this balance can lead to reduced stress and a more fulfilling life outside of work.",
                            CreatedDate = new DateTime(2023, 11, 10, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "Achieving harmony in your daily life",
                            Title = "Balancing Work and Personal Life"
                        },
                        new
                        {
                            ArticleId = 12,
                            CategoryId = 3,
                            Content = "Healthy relationships are a cornerstone of a fulfilling life. This article delves into the key principles of building and maintaining healthy connections with friends, family, and partners. Learn effective communication, conflict resolution, and emotional intelligence to foster positive and meaningful relationships in your life.",
                            CreatedDate = new DateTime(2023, 11, 10, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "Nurturing meaningful connections in life",
                            Title = "Building Healthy Relationships"
                        },
                        new
                        {
                            ArticleId = 14,
                            CategoryId = 5,
                            Content = "Teenage years are a crucial time for personal development. This article focuses on promoting healthy habits for teenagers, including proper nutrition, exercise, and mental well-being. Discover how to make positive lifestyle choices that can set the foundation for a healthy and fulfilling adulthood.",
                            CreatedDate = new DateTime(2023, 11, 10, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "Promoting well-being in teenage years",
                            Title = "Healthy Habits for Teens"
                        },
                        new
                        {
                            ArticleId = 15,
                            CategoryId = 5,
                            Content = "Peer pressure is a common experience for teenagers. This article provides guidance on how to navigate peer pressure and make informed choices in social situations. Learn to assert your values, set boundaries, and build strong, supportive friendships during your teenage years.",
                            CreatedDate = new DateTime(2023, 11, 10, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "Making informed choices in social situations",
                            Title = "Navigating Peer Pressure"
                        },
                        new
                        {
                            ArticleId = 16,
                            CategoryId = 5,
                            Content = "As a teenager, it's never too early to start exploring potential career paths. This article offers insights and tips on how to begin your career exploration journey. Learn about different career options, educational paths, and how to set goals for your future. By starting early, you can make informed decisions about your career.",
                            CreatedDate = new DateTime(2023, 11, 10, 4, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "Discovering your future path",
                            Title = "Career Exploration for Teens"
                        },
                        new
                        {
                            ArticleId = 17,
                            CategoryId = 6,
                            Content = "Early childhood education plays a crucial role in a child's development. This article explores the significance of quality preschool and kindergarten programs in preparing children for academic success and social growth. Discover the long-term benefits of early education and how it can set the stage for a lifetime of learning.",
                            CreatedDate = new DateTime(2023, 11, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "Laying the foundation for lifelong learning",
                            Title = "The Importance of Early Childhood Education"
                        },
                        new
                        {
                            ArticleId = 18,
                            CategoryId = 6,
                            Content = "Online learning has become increasingly prevalent in the education landscape. This article discusses the evolution of online education and its impact on traditional learning methods. Explore the advantages and challenges of virtual classrooms and how they are shaping the future of education.",
                            CreatedDate = new DateTime(2023, 11, 11, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "Adapting to the digital age of learning",
                            Title = "Online Learning and the Future of Education"
                        },
                        new
                        {
                            ArticleId = 19,
                            CategoryId = 6,
                            Content = "Teachers are the cornerstone of education. This article highlights the vital role that teachers play in fostering a love for learning, critical thinking, and personal growth in students. Learn about the challenges educators face and the rewards of inspiring young minds to achieve their full potential.",
                            CreatedDate = new DateTime(2023, 11, 11, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "Nurturing young minds for a brighter future",
                            Title = "The Role of Teachers in Fostering Learning"
                        },
                        new
                        {
                            ArticleId = 20,
                            CategoryId = 7,
                            Content = "Travel enthusiasts, get ready to embark on an exploration of exotic destinations around the world. This article takes you on a journey to breathtaking locations, from tropical paradises to historical wonders. Discover travel tips, local cultures, and the wonders that await those who seek new horizons.",
                            CreatedDate = new DateTime(2023, 11, 11, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "Adventures in far-off lands",
                            Title = "Exploring Exotic Destinations"
                        },
                        new
                        {
                            ArticleId = 21,
                            CategoryId = 7,
                            Content = "As travelers, it's crucial to embrace sustainable tourism practices. This article emphasizes the importance of responsible and eco-friendly travel. Learn how to minimize your impact on the environment, support local communities, and contribute to the preservation of natural beauty while enjoying your adventures.",
                            CreatedDate = new DateTime(2023, 11, 11, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "Preserving the beauty of our planet",
                            Title = "Sustainable Tourism Practices"
                        },
                        new
                        {
                            ArticleId = 22,
                            CategoryId = 7,
                            Content = "One of the joys of travel is indulging in diverse and delectable culinary experiences. This article celebrates culinary tourism, where you can savor the flavors of various cuisines worldwide. From street food to fine dining, embark on a gastronomic journey that will tantalize your taste buds and create unforgettable memories.",
                            CreatedDate = new DateTime(2023, 11, 11, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "Tasting the world's delicious cuisine",
                            Title = "Culinary Tourism: Savoring Global Flavors"
                        },
                        new
                        {
                            ArticleId = 23,
                            CategoryId = 8,
                            Content = "The world of cinema has witnessed a remarkable evolution over the decades. This article takes you on a journey through the history of filmmaking, from the early days of silent movies to the era of modern blockbusters. Explore the impact of technology, storytelling, and cultural influences on the film industry.",
                            CreatedDate = new DateTime(2023, 11, 11, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "From silent films to modern blockbusters",
                            Title = "The Evolution of Cinema"
                        },
                        new
                        {
                            ArticleId = 24,
                            CategoryId = 8,
                            Content = "Music is a universal language that has been an integral part of human culture for centuries. This article traces the evolution of music through various genres, styles, and eras. From classical compositions to contemporary hits, immerse yourself in the world of melodies and rhythms that have shaped our lives.",
                            CreatedDate = new DateTime(2023, 11, 11, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "A journey of melodies and rhythms",
                            Title = "Music Through the Ages"
                        },
                        new
                        {
                            ArticleId = 25,
                            CategoryId = 8,
                            Content = "Video games have evolved from simple amusements to a major form of entertainment and a cultural phenomenon. This article explores the multifaceted world of gaming, its influence on society, and its role in education, art, and technology. Dive into the world of gaming and its broader impact on our lives.",
                            CreatedDate = new DateTime(2023, 11, 11, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "The impact of video games on society",
                            Title = "Gaming: Beyond Entertainment"
                        },
                        new
                        {
                            ArticleId = 26,
                            CategoryId = 9,
                            Content = "Artificial Intelligence (AI) is revolutionizing industries and reshaping the way we live and work. This article delves into the rapid advancements in AI technology, its applications in various sectors, and the ethical considerations surrounding its use. Discover how AI is changing the landscape of technology and society as a whole.",
                            CreatedDate = new DateTime(2023, 11, 11, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "Exploring AI's impact on our world",
                            Title = "The Rise of Artificial Intelligence"
                        },
                        new
                        {
                            ArticleId = 27,
                            CategoryId = 9,
                            Content = "In an era of increasing digitalization, cybersecurity is paramount. This article explores the evolving landscape of cybersecurity, from data breaches to protective measures. Learn about the challenges in safeguarding digital information and the strategies to defend against cyber threats and attacks.",
                            CreatedDate = new DateTime(2023, 11, 11, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "Protecting data in an interconnected world",
                            Title = "Cybersecurity in the Digital Age"
                        },
                        new
                        {
                            ArticleId = 28,
                            CategoryId = 9,
                            Content = "The tech industry is constantly evolving. This article provides insights into the emerging technology trends of 2023, including 5G, blockchain, and the Internet of Things (IoT). Stay informed about the latest innovations that are shaping the way we live and the future of technology.",
                            CreatedDate = new DateTime(2023, 11, 11, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "A glimpse into the future of technology",
                            Title = "Emerging Tech Trends in 2023"
                        },
                        new
                        {
                            ArticleId = 29,
                            CategoryId = 10,
                            Content = "Sustainable fashion is a growing trend that prioritizes eco-friendly materials and ethical production practices. This article explores the latest trends in sustainable fashion, from upcycled clothing to environmentally conscious brands. Discover how you can make stylish choices that are also good for the planet.",
                            CreatedDate = new DateTime(2023, 11, 11, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "Eco-friendly style for a greener world",
                            Title = "Trends in Sustainable Fashion"
                        },
                        new
                        {
                            ArticleId = 30,
                            CategoryId = 10,
                            Content = "Street style has evolved from underground subcultures to influencing mainstream fashion. This article explores the influence of street fashion on the broader culture, from hip-hop to skater aesthetics. Discover how street style has become a major force in the fashion industry and how it reflects cultural movements.",
                            CreatedDate = new DateTime(2023, 11, 11, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "Urban fashion's impact on mainstream culture",
                            Title = "The Influence of Street Style"
                        },
                        new
                        {
                            ArticleId = 31,
                            CategoryId = 10,
                            Content = "Accessories are an essential part of any fashion ensemble. This article delves into the art of accessorizing, from statement jewelry to handbags and scarves. Learn how the right accessories can transform your look and add a personal touch to your fashion choices.",
                            CreatedDate = new DateTime(2023, 11, 11, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "Elevate your style with the right accessories",
                            Title = "The Art of Accessorizing"
                        });
                });

            modelBuilder.Entity("BusinessObject.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Politics"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Economics"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Life"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Health"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "For teens"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Education"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Tourism"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Entertainment"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Technology"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Fashion"
                        });
                });

            modelBuilder.Entity("BusinessObject.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"), 1L, 1);

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("CommentContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CommentTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("MemberId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("BusinessObject.Models.Member", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "77cbb596-f510-4b51-a89e-b7a4535a6ee1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a2291019-9eac-4afe-8c75-f2b58a1ea1a5",
                            Email = "admin@dailynews.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@DAILYNEWSNEWS.COM",
                            NormalizedUserName = "ADMIN@DAILYNEWSNEWS.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEJgng3rxR9pn7cXdf/SIOIfMBVWTO2o3865UD3IMJuW+2aKvSxDfDE2ys5ZPxyE69g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ecdff81b-aae2-4fe9-820d-ae245d9bebf8",
                            TwoFactorEnabled = false,
                            UserName = "admin@dailynews.com"
                        },
                        new
                        {
                            Id = "d1029da4-59f0-4643-ab94-90642bf89062",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "13c5f42d-e233-4349-a3a2-ed2094aa048c",
                            Email = "writer@dailynews.com",
                            EmailConfirmed = false,
                            FirstName = "Writer",
                            LastName = "Isaac",
                            LockoutEnabled = false,
                            NormalizedEmail = "WRITER@DAILYNEWSNEWS.COM",
                            NormalizedUserName = "WRITER@DAILYNEWSNEWS.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEA+y4W1GlpkUlc/xU8LfHbvMfdUEfId9X3PoQIzgzTnKk4IcJkw+wO7SjTkm2+wdMw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8f51bed5-5d4a-45d9-9d38-348cf96159a8",
                            TwoFactorEnabled = false,
                            UserName = "writer@dailynews.com"
                        },
                        new
                        {
                            Id = "594a123f-674c-4c8d-add8-0a4d517558a5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9a841e95-3429-4af0-8618-5b731df5fc45",
                            Email = "user@dailynews.com",
                            EmailConfirmed = false,
                            FirstName = "User",
                            LastName = "Benjamin",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@DAILYNEWSNEWS.COM",
                            NormalizedUserName = "USER@DAILYNEWSNEWS.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAELi/GMYaXWG+0Koa+FkQrBpDDF7NtwLPg+MkJAYjb2Y248D7EXKuAHUfSxR6qybDGQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bd98d380-216d-4474-9dc0-cc0e48bb2e96",
                            TwoFactorEnabled = false,
                            UserName = "user@dailynews.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ea084acf-14ef-4138-96be-1b3db76e405b",
                            ConcurrencyStamp = "a787bf9e-62d6-465c-9030-38087dfb0412",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "a8dff705-c4e8-4a75-9090-22910978b7aa",
                            ConcurrencyStamp = "1208b015-b411-421c-94cd-29ab2971382c",
                            Name = "Writer",
                            NormalizedName = "WRITER"
                        },
                        new
                        {
                            Id = "cc84ea3c-3288-4f5f-bf25-09444f232dd9",
                            ConcurrencyStamp = "831e98d5-38e8-4c24-a739-477ecabcab97",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "b12f815d-6da0-4fb7-a3e9-b05fa8331eaf",
                            ConcurrencyStamp = "a52339aa-ccfb-4351-89b1-3b3b99519e94",
                            Name = "Guest",
                            NormalizedName = "GUEST"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "77cbb596-f510-4b51-a89e-b7a4535a6ee1",
                            RoleId = "ea084acf-14ef-4138-96be-1b3db76e405b"
                        },
                        new
                        {
                            UserId = "d1029da4-59f0-4643-ab94-90642bf89062",
                            RoleId = "a8dff705-c4e8-4a75-9090-22910978b7aa"
                        },
                        new
                        {
                            UserId = "594a123f-674c-4c8d-add8-0a4d517558a5",
                            RoleId = "cc84ea3c-3288-4f5f-bf25-09444f232dd9"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Models.Article", b =>
                {
                    b.HasOne("BusinessObject.Models.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BusinessObject.Models.Comment", b =>
                {
                    b.HasOne("BusinessObject.Models.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BusinessObject.Models.Member", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BusinessObject.Models.Member", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Models.Member", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BusinessObject.Models.Member", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessObject.Models.Article", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("BusinessObject.Models.Category", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
